version: '3.8'
services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    env_file:
      - ./.env
    ports:
      - "55432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: fastapi_backend
    depends_on:
      - db
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    restart: unless-stopped

volumes:
  pg_data:
